openapi: 3.1.0
info:
  title: Examples
  description: Examples fixture
  version: 1.0.0
  
paths:
  /matching-examples:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
              required:
                - date
            examples:
              date1:
                summary: date1
                value:
                  date: "2020-12-09T17:25:40.008307"
              date2:
                summary: date2
                value:
                  date: "2024-01-24T12:37:24.000Z"

      responses:
        '202':
          description: date response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties: 
                  message:
                    type: string
              examples: 
                date1:
                  summary: date1
                  value:
                    message: date received 1
                date2:
                  summary: date2
                  value:
                    message: date received 2

  /non-matching-examples:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
              required:
                - date
            examples:
              date1req:
                summary: date1
                value:
                  date: "2020-12-09T17:25:40.008307"
              date2req:
                summary: date2
                value:
                  date: "2024-01-24T12:37:24.000Z"

      responses:
        '202':
          description: date response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties: 
                  message:
                    type: string
              examples: 
                date1res:
                  summary: date1
                  value:
                    message: date received 1
                date2res:
                  summary: date2
                  value:
                    message: date received 2
  
  /more-requests:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
              required:
                - date
            examples:
              date1req:
                summary: date1
                value:
                  date: "2020-12-09T17:25:40.008307"
              date2req:
                summary: date2
                value:
                  date: "2024-01-24T12:37:24.000Z"

      responses:
        '202':
          description: date response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties: 
                  message:
                    type: string
              examples: 
                date1res:
                  summary: date1
                  value:
                    message: date received 1

  
  /more-responses:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
              required:
                - date
            examples:
              date1req:
                summary: date1
                value:
                  date: "2020-12-09T17:25:40.008307"

      responses:
        '202':
          description: date response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties: 
                  message:
                    type: string
              examples: 
                date1res:
                  summary: date1
                  value:
                    message: date received 1
                date2res:
                  summary: date2
                  value:
                    message: date received 2

  /post-empty-response:
    post:
      description: empty response
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
              required:
                - date
            examples:
              date1req:
                summary: date1
                value:
                  date: "2020-12-09T17:25:40.008307"

  /single-example:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                date:
                  type: string
                  format: date-time
              required:
                - date
            example:
              date: "2020-12-09T17:25:40.008307"

      responses:
        '202':
          description: date response
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties: 
                  message:
                    type: string
              example: 
                message: date received 1
    
  /request-body-reference:
    post:
      parameters:
        - required: true
          schema:
            type: string
            format: date
          example: '2024-05-25'
          name: version
          in: header
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SampleSchema'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Sample200Response'


components:
  schemas:
    SampleSchema:
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        another_string:
          type: string
          format: uuid
        nested_object:
          $ref: '#/components/schemas/NestedSchema'
      additionalProperties: false
      type: object
      required:
        - id
        - name
        - nested_object

    NestedSchema:
      type: string
      enum:
        - var1
        - var2

    Sample200Response:
      properties:
        message:
          type: string
